### ISSUE TITLE
LICENSE file needs to be completed

### ISSUE THREAD

**Issue by AKurilin** [freckle/yesod-page-cursor#11]
Hey friends. The LICENSE file is just the template for now, it should have Renaissance Learning Inc as the rights holder. Also please consider using MIT instead of BSD-3 for simplicity.

**Comment by pbrisbin** [comment]
I can make it MIT.

> it should have Renaissance Learning Inc

We should probably look across all our OSS for this bit? I never gave it much thought, and always used "Freckle Engineering" I think.

**Comment by AKurilin** [comment]
Yeah, I'd actually check what other RL OSS libraries do as of today and follow suit there, for consistency.

**Comment by pbrisbin** [comment]
See freckle/guides#52.
